using RpcTyped;

namespace RevivalRevived.Components;

/// <summary>
/// Routed RPCs for the downed/revive feature, registered on every Player's
/// ZNetView. Wire names, invoke shapes and handler signatures are generated by
/// RpcTyped -- there are no loose RPC name strings anywhere; ZDO field access
/// is likewise typed via the ZdoTyped schemas (<see cref="DownedPlayerZdo"/>
/// and <see cref="DownedMarker.View"/>).
/// </summary>
[RpcSet("RevivalRevived")]
public partial struct DownedRpcs {
    /// <summary>Broadcast: play the downed poof at the player (state is ZDO-driven).</summary>
    [Rpc] public partial void OnDowned();

    /// <summary>Reviver -> owner: "someone is channeling", pauses the bleed-out window.</summary>
    [Rpc] public partial void Channel();

    /// <summary>Reviver -> owner: the (peer-authoritative) hold completed, execute the revive.</summary>
    [Rpc] public partial void DoRevive();
}
