using RpcTyped;

namespace RevivalRevived.Components;

/// <summary>
/// Routed RPCs for the downed/revive feature, registered on every Player's
/// ZNetView. Wire names, invoke shapes and handler signatures are generated by
/// RpcTyped -- there are no loose RPC name strings anywhere; ZDO field access
/// is likewise typed via the ZdoTyped schemas (<see cref="DownedPlayerZdo"/>
/// and <see cref="DownedMarker.View"/>).
///
/// The revive is owner-authoritative: a reviver only sends <see cref="Channel"/>
/// pings while it holds, and the downed player's own owner accumulates the
/// progress, publishes it, and revives itself at completion. There is no
/// "do the revive" RPC and no cross-client marker writing -- so nothing to
/// race.
/// </summary>
[RpcSet("RevivalRevived")]
public partial struct DownedRpcs {
    /// <summary>Broadcast: play the downed poof at the player (state is ZDO-driven).</summary>
    [Rpc] public partial void OnDowned();

    /// <summary>Reviver -> owner: "I am channeling a revive this moment." The owner accumulates progress and revives itself.</summary>
    [Rpc] public partial void Channel();
}
